### ISSUE TITLE
Crash Server if environment variables aren't there

### ISSUE THREAD

**Issue by m4v15** [FACK1/ReWorks#106]
- If you don't have environment variables, your app won't be able to do what it is supposed to.
- You want to crash the server if the environment variables aren't present, so that you (or another developer) knows the reason why the app doesn't work
- For example, I was able to get this to run but I didn't have the `S3` environment variables and there was no clear error anywhere.
- In files where you use environment variables, you should check they have been imported, and throw an error if not:

```js
// configure the keys for accessing AWS
AWS.config.update({
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
});

if (!process.env.AWS_ACCESS_KEY_ID) {
  throw new Error('Missing S3 ACCESS key env var');
}
```

This stops your server from even starting if you don't have the variables, so there is no chance of the end user being able to use an app that is broken in this way.

**Comment by m4v15** [comment]
When you or another developer tries to run or deploy the app, it won't work until the environment variables are there.

**Comment by Hadeel-Salamin** [comment]
@m4v15 this is fixed too :hammer:, I guess
