### ISSUE TITLE
As a user, I want to see the headline details about the photo I uploaded.

### ISSUE THREAD

**Issue by alha69** [FACK1/ReWorks#3]

**Comment by orjwan98** [comment]
1- Render the `/getDetailsPage` component with retrieved data.

**Comment by amanshawar** [comment]
Show the result of the response from clarify api

**Comment by Hadeel-Salamin** [comment]
Components: UploadPhoto, Item

Procedure:
1- Post the photo URL to remove background API and get back a new photo URL.
2- Post the new photo URL to Clarifai APIs and get back all tag names with their percentage (item details).
3- Save item details in (Object || Local Storage || Json File)
4- Render Item component and show All item details on it.
