### ISSUE TITLE
As a user, I want to login to save my items and data.

### ISSUE THREAD

**Issue by orjwan98** [FACK1/ReWorks#8]

**Comment by amanshawar** [comment]
Components: login

Procedure:
1- Fill form of username and password
2- Click login
3- Get the data of the username from DATABASE
4- Encrypt the password  and compare it will the password from the form 
5- Render allItems component and show All items for the user.

**Comment by amanshawar** [comment]
Components: login

Procedure:
1- Fill form of username and password
2- Click login
3- Get the data of the username from DATABASE
4- Encrypt the password  and compare it will the password from the form 
5-
