### ISSUE TITLE
No Local Install instructions

### ISSUE THREAD

**Issue by m4v15** [FACK1/ReWorks#92]
Could you please add information on how to run this locally:

- Technologies required (Node, Postgres if using a local database)
- Environment variables - variables needed, what to call the file, where to put the file

**Comment by Hadeel-Salamin** [comment]
@m4v15 if you are happy how is it now can you close this issue, please? :roll_eyes:

**Comment by m4v15** [comment]
Good works, except for 2 things:

The mongo db url structure you put is wrong, it should be:

`mongodb://[username:password@][host]:[port]/[databasename]`

not

`mongodb://localhost:password/username`

And the repo is calle `ReWorks` with and 's' but you tell them to `cd ReWork`

Small things but they make it look a bit sloppy.

**Comment by orjwan98** [comment]
@m4v15  Fixed it boss! :+1:
